// <auto-generated />
namespace pruebaMvc01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class segunda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(segunda));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131807532_segunda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
